package com.anthonyrodriguez.papersage_backend.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * Response returned by the grounded answer endpoint ({@code POST /api/v1/papers/ask}).
 * Contains the original question, the AI-generated grounded answer, and references
 * to the source chunks that were used as context.
 *
 * @param question the user's original question
 * @param answer   the grounded answer generated by Gemini using only the retrieved context
 * @param sources  lightweight references to the chunks used as context for the answer
 */
public record AnswerResponse(
        @JsonProperty("question") String question,
        @JsonProperty("answer") String answer,
        @JsonProperty("sources") List<SourceReference> sources
) {
}
