package com.anthonyrodriguez.papersage_backend.dto;

/**
 * Pairs a {@link TextChunk} with its embedding vector generated by the Gemini API.
 * Used internally for in-memory semantic retrieval — not exposed in API responses.
 *
 * @param chunk     the original text chunk
 * @param embedding the embedding vector (768 dimensions from Gemini text-embedding-004)
 */
public record EmbeddedChunk(
        TextChunk chunk,
        float[] embedding
) {
}
